id: P004334
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:12:03.641541
source_metadata:
  id: bdr:W8LS20278
  title: བློ་མང་དོན་གྲུབ།
  author: ''
  volumes:
    bf5bbe7c803542c193fa2222a5f13e47:
      image_group_id: I8LS20280
      title: ''
      volume_number: 1
      total_pages: 273
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
