id: IEF54F898
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T10:09:31+00:00'
last_modified: '2022-06-07T22:04:35.264998+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20278
  title: བློ་མང་དོན་གྲུབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    7C62:
      image_group_id: I8LS20280
      title: ''
      total_pages: 273
      order: 1
      base_file: 7C62.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
